name: Setup Node

description: Setup up Node.js, restores NPM cache and installs dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/package-lock.json'
        cache: 'npm'
        node-version-file: .nvmrc
    - run: npm ci
      shell: bash
