name: Hostinger Deployment Staging

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hemilabs/actions/setup-node-env@main
      - name: Deploy portal
        uses: ./.github/actions/deploy-portal
        with:
          # hostinger env variables
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
          HOSTINGER_PORT: ${{ secrets.HOSTINGER_PORT }}
          HOSTINGER_SSH_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
          HOSTINGER_TARGET: domains/${{ vars.HEMI_DOMAIN_STAGING }}/public_html/app
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          # next env variables to build the portal
          NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET: $ {{ vars.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET_STAGING }}
          # NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA: ${{ vars.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA_STAGING }}
          NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET: ${{ vars.NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET_STAGING }}
          NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA: ${{ vars.NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA_STAGING }}
          NEXT_PUBLIC_ENABLE_ANALYTICS: false
          NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL: false
          NEXT_PUBLIC_FEATURE_FLAG_ENABLE_MAINNET: true
