name: Hostinger Deployment Prod

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hemilabs/actions/setup-node-env@main
      - name: Deploy portal
        uses: ./.github/actions/deploy-portal
        with:
          # hostinger env variables
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
          HOSTINGER_PORT: ${{ secrets.HOSTINGER_PORT }}
          HOSTINGER_SSH_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
          HOSTINGER_TARGET: domains/${{ vars.HEMI_DOMAIN_PROD }}/public_html/app
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          # next env variables to build the portal
          NEXT_PUBLIC_ANALYTICS_URL: ${{ vars.NEXT_PUBLIC_ANALYTICS_URL }}
          NEXT_PUBLIC_ANALYTICS_WEBSITE_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_WEBSITE_ID_PROD }}
          NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET: ${{ vars.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_MAINNET_PROD }}
          # NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA: ${{ vars.NEXT_PUBLIC_CUSTOM_RPC_URL_HEMI_SEPOLIA_PROD }}
          NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET: ${{ vars.NEXT_PUBLIC_CUSTOM_RPC_URL_MAINNET_PROD }}
          # NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA: ${{ vars.NEXT_PUBLIC_CUSTOM_RPC_URL_SEPOLIA_PROD }}
          NEXT_PUBLIC_ENABLE_ANALYTICS: true
          NEXT_PUBLIC_FEATURE_FLAG_ENABLE_BTC_TUNNEL: false
          NEXT_PUBLIC_FEATURE_FLAG_ENABLE_MAINNET: false
          NEXT_PUBLIC_RELEASE_VERSION: ${{ github.event.release.name }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ vars.NEXT_PUBLIC_SENTRY_DSN_PROD }}
          NEXT_PUBLIC_SENTRY_ENVIRONMENT: production
          NEXT_PUBLIC_TRACES_SAMPLE_RATE: 1.0
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN_PROD }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_INTEGRATION_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ format('{0}@{1}', vars.SENTRY_PROJECT, github.event.release.name) }}
