on:
  workflow_call:
    inputs:
      app-name:
        description: 'The app being deployed'
        required: true
        type: string
      environment:
        description: 'The deployment environment'
        required: true
        type: string
      reference:
        description: 'Additional reference to add to the notification'
        required: false
        default: ''
        type: string
      slack-channel:
        description: 'The name of the Slack channel'
        required: true
        type: string
      slack-mention:
        description: 'The mention to include in the message'
        default: <!here>
        type: string
      slack-webhook-url:
        description: 'The Slack incoming webhook URL'
        required: true
        type: string
      status:
        description: 'The deployment status'
        required: true
        type: string

jobs:
  send-message:
    runs-on: ubuntu-latest
    env:
      SEPARATOR: ${{ inputs.reference != '' && '\n' || '' }}
    steps:
      - uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "channel": "${{ inputs.slack-channel }}",
              "username": "Github Actions Deployment Monitor",
              "text": ${{ format('{0} Deployement of {1} to {2} {3}{4}{5}', inputs.slack-mention, inputs.app-name, inputs.environment, inputs.status, env.SEPARATOR, inputs.reference) }},
              "icon_emoji": ":github:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
